"""add category/dedup_key/metadata_json to notifications

Revision ID: a1b2c3d4e5f6
Revises: 8a7d30a5c4d4
Create Date: 2026-08-18 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, Sequence[str], None] = "8a7d30a5c4d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite does not support ALTER COLUMN / DROP DEFAULT, so add the column
    # with a server_default (backfills existing rows) and leave it; the model's
    # default handles new rows.
    op.add_column(
        "notifications",
        sa.Column("category", sa.String(length=50), nullable=False, server_default="system"),
    )
    op.add_column("notifications", sa.Column("dedup_key", sa.String(length=255), nullable=True))
    op.add_column("notifications", sa.Column("metadata_json", sa.JSON(), nullable=True))
    op.create_index(op.f("ix_notifications_category"), "notifications", ["category"], unique=False)
    op.create_index(op.f("ix_notifications_dedup_key"), "notifications", ["dedup_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_dedup_key"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_category"), table_name="notifications")
    op.drop_column("notifications", "metadata_json")
    op.drop_column("notifications", "dedup_key")
    op.drop_column("notifications", "category")
    # ### end Alembic commands ###
